id: P3F4A48A7
initial_creation_type: input
source_metadata:
  title: Āpastambaśulbasūtra with the commentaries of Kapardin, Karavinda and Sundararāja
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Veda -- Vedāṅga -- Śrautasūtra
  data entry: members of the Sansknet Project
  contribution to GRETIL: members of the Sansknet Project
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T14:49:12.068353'
last_modified_at: '2022-03-09T14:49:12.068368'
